/*
 * Copyright (C) 2026 XFCE4 MorphOS Workbench Plugin Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include "morphos-workbench.h"

/* ------------------------------------------------------------------ *
 *  CSS - three Ambient themes (Classic / Dark / Light)
 *  ------------------------------------------------------------------ */

static const gchar *MWB_CSS =
  /* ---- structural base (theme independent) ---- */
  ".mwb-plugin, .mwb-plugin * {"
  "  -gtk-icon-style: regular;"
  "  -gtk-icon-transform: none;"
  "}"
  ".mwb-plugin {"
  "  background: transparent;"
  "  background-color: transparent;"
  "  border: none;"
  "}"
  ".mwb-bar {"
  "  padding: 0;"
  "}"
  ".mwb-button {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  padding: 0 6px;"
  "  min-height: 24px;"
  "  font-weight: 700;"
  "  font-size: 11px;"
  "  letter-spacing: 0.15px;"
  "}"
  ".mwb-button:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-button:active, .mwb-button.open {"
  "  color: #ffffff;"
  "}"
  ".mwb-logo {"
  "  padding: 0 4px;"
  "}"
  ".mwb-clocks {"
  "  background: transparent;"
  "  padding: 0 4px;"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  letter-spacing: 0.2px;"
  "}"
  ".mwb-separator {"
  "  min-width: 1px;"
  "  margin: 3px 2px;"
  "}"
  ".mwb-screenbar-divider {"
  "  min-width: 1px;"
  "  margin: 3px 3px;"
  "}"
  ".mwb-popup {"
  "  background-color: #18263a;"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  border-radius: 8px;"
  "  box-shadow: 0 8px 22px alpha(#000000, 0.60);"
  "  padding: 8px 10px;"
  "}"
  ".mwb-popup label, .mwb-popup calendar {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-vol-popup {"
  "  min-width: 300px;"
  "}"
  ".mwb-pop-icon {"
  "  min-width: 16px;"
  "  min-height: 16px;"
  "}"
  ".mwb-pop-title {"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "}"
  ".mwb-pop-section-hdr {"
  "  font-size: 11px;"
  "  font-weight: 600;"
  "}"
  ".mwb-vol-scale trough {"
  "  min-height: 6px;"
  "  border-radius: 3px;"
  "}"
  ".mwb-vol-scale highlight {"
  "  border-radius: 3px;"
  "}"
  ".mwb-vol-scale slider {"
  "  min-width: 14px;"
  "  min-height: 14px;"
  "  border-radius: 4px;"
  "}"
  ".mwb-vol-badge {"
  "  font-family: monospace;"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  padding: 1px 5px;"
  "  border-radius: 4px;"
  "}"
  ".mwb-vol-card, .mwb-notify-card, .mwb-streams-card {"
  "  background: transparent !important;"
  "  background-color: transparent !important;"
  "  background-image: none !important;"
  "  border: none !important;"
  "  box-shadow: none !important;"
  "  padding: 4px 2px;"
  "}"
  ".mwb-playing-card {"
  "  border-radius: 6px;"
  "  padding: 6px 8px;"
  "}"
  ".mwb-playing-art-frame {"
  "  border-radius: 4px;"
  "  padding: 2px;"
  "}"
  ".mwb-playing-title {"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "}"
  ".mwb-playing-artist {"
  "  font-size: 11px;"
  "  font-weight: 500;"
  "}"
  ".mwb-media-toolbar {"
  "  margin-top: 4px;"
  "}"
  ".mwb-media-btn {"
  "  border-radius: 4px;"
  "  padding: 2px 6px;"
  "  min-height: 22px;"
  "  min-width: 24px;"
  "}"
  ".mwb-media-play-btn {"
  "  border-radius: 14px;"
  "  padding: 4px 12px;"
  "  min-height: 28px;"
  "  min-width: 36px;"
  "}"
  ".mwb-streams-card {"
  "  border-radius: 8px;"
  "  padding: 6px 10px;"
  "}"
  ".mwb-stream-row {"
  "  padding: 2px 0;"
  "}"
  ".mwb-stream-label {"
  "  font-size: 11px;"
  "  font-weight: 600;"
  "}"
  ".mwb-stream-empty {"
  "  font-size: 11px;"
  "  font-style: italic;"
  "  padding: 4px 0;"
  "}"
  ".mwb-mixer-btn {"
  "  border-radius: 6px;"
  "  padding: 6px 12px;"
  "  min-height: 30px;"
  "  font-weight: 600;"
  "  font-size: 11px;"
  "}"
  ".mwb-vol-scale trough {"
  "  min-height: 8px;"
  "  border-radius: 4px;"
  "  margin: 4px 0;"
  "}"
  ".mwb-vol-scale highlight {"
  "  border-radius: 4px;"
  "}"
  ".mwb-vol-scale slider {"
  "  min-width: 16px;"
  "  min-height: 16px;"
  "  border-radius: 8px;"
  "  margin: -4px 0;"
  "}"
  ".mwb-vol-scale slider:hover {"
  "  min-width: 18px;"
  "  min-height: 18px;"
  "  margin: -5px 0;"
  "}"
  ".mwb-gear-btn {"
  "  min-width: 24px;"
  "  min-height: 24px;"
  "  padding: 2px 4px;"
  "  border-radius: 4px;"
  "}"
  ".mwb-batt-grid-lbl {"
  "  font-size: 10px;"
  "  opacity: 0.75;"
  "}"
  ".mwb-batt-grid-val {"
  "  font-size: 11px;"
  "  font-weight: 600;"
  "}"
  ".mwb-prof-btn {"
  "  min-height: 26px;"
  "  font-size: 11px;"
  "  font-weight: 600;"
  "  padding: 3px 6px;"
  "  border-radius: 4px;"
  "}"
  /* ---- base menu (same chromatic look as the workbench bar) ---- */
  ".mwb-menu {"
  "  background-color: rgba(28, 42, 64, 0.90);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  border-radius: 4px;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.55);"
  "  padding: 2px 0;"
  "}"
  ".mwb-menu > menuitem {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#6ba3d9, 0.8) 0%, alpha(#3a72ad, 0.8) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.10);"
  "  min-height: 1px;"
  "  margin: 2px 0;"
  "}"
  ".mwb-settings, dialog.mwb-settings, window.mwb-settings {"
  "  background-color: @theme_bg_color;"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-settings stack, .mwb-settings .stack {"
  "  background-color: @theme_bg_color;"
  "}"
  ".mwb-settings list, .mwb-settings row {"
  "  background-color: @theme_base_color;"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-settings-section {"
  "  font-weight: 700;"
  "  padding: 4px 6px;"
  "  border-top: 1px solid alpha(#ffffff, 0.28);"
  "  border-bottom: 1px solid alpha(#000000, 0.35);"
  "}"
  ".mwb-gaugebox {"
  "  background: transparent;"
  "  padding: 0 2px;"
  "  min-height: 24px;"
  "  border: none;"
  "  box-shadow: none;"
  "}"
  ".mwb-vgauge {"
  "  min-width: 76px;"
  "  min-height: 14px;"
  "  background: transparent;"
  "}"
  ".mwb-vgauge-label {"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  padding: 0 1px;"
  "}"
  ".mwb-gauge-value {"
  "  min-width: 34px;"
  "  font-family: monospace;"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  padding: 0 2px;"
  "}"
  ".mwb-lamp {"
  "  min-width: 8px;"
  "  min-height: 8px;"
  "  border-radius: 50%;"
  "  margin: 0 1px;"
  "}"
  ".mwb-screenbar-item {"
  "  background: transparent;"
  "  font-size: 11px;"
  "  font-weight: 600;"
  "  padding: 0 2px;"
  "  min-height: 24px;"
  "}"
  ".mwb-volbutton, .mwb-clockbtn {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  padding: 0 4px;"
  "  min-height: 24px;"
  "}"
  ".mwb-volbutton:hover, .mwb-clockbtn:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-island {"
  "  margin: 2px 2px;"
  "  padding: 0 4px;"
  "  min-height: 24px;"
  "  border: 1px solid alpha(#000000, 0.40);"
  "  border-radius: 4px;"
  "  box-shadow: none;"
  "}"
  ".mwb-volbutton image, .mwb-clockbtn image {"
  "  min-width: 16px;"
  "  min-height: 16px;"
  "}"
  ".mwb-badge {"
  "  background-color: #3b82f6;"
  "  color: #ffffff;"
  "  font-size: 10px;"
  "  font-weight: 700;"
  "  border-radius: 8px;"
  "  padding: 1px 5px;"
  "  margin-left: 2px;"
  "  min-width: 14px;"
  "  text-align: center;"
  "}"
  ".mwb-notify-scroll {"
  "  min-width: 320px;"
  "  max-height: 360px;"
  "}"
  ".mwb-notify-scroll viewport {"
  "  background: transparent;"
  "}"
  ".mwb-notify-card {"
  "  padding: 8px 10px;"
  "  border-radius: 8px;"
  "  margin-bottom: 4px;"
  "}"
  ".mwb-notify-app-name {"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  letter-spacing: 0.2px;"
  "}"
  ".mwb-notify-time {"
  "  font-size: 10px;"
  "  opacity: 0.75;"
  "}"
  ".mwb-notify-summary {"
  "  font-size: 12px;"
  "  font-weight: 700;"
  "  margin-top: 2px;"
  "}"
  ".mwb-notify-body {"
  "  font-size: 11px;"
  "  opacity: 0.88;"
  "  margin-top: 2px;"
  "}"
  ".mwb-notify-dismiss {"
  "  border-radius: 50%;"
  "  min-width: 18px;"
  "  min-height: 18px;"
  "  padding: 0;"
  "  background: transparent;"
  "  border: none;"
  "  opacity: 0.7;"
  "}"
  ".mwb-notify-dismiss:hover {"
  "  opacity: 1.0;"
  "}"
  ".mwb-theme-classic .mwb-volbutton, .mwb-theme-classic .mwb-clockbtn,"
  ".mwb-theme-dark .mwb-volbutton, .mwb-theme-dark .mwb-clockbtn {"
  "  border-top-color: alpha(#ffffff, 0.12);"
  "  border-left-color: alpha(#ffffff, 0.08);"
  "  border-right-color: alpha(#000000, 0.45);"
  "  border-bottom-color: alpha(#000000, 0.45);"
  "}"
  ".mwb-theme-light .mwb-volbutton, .mwb-theme-light .mwb-clockbtn {"
  "  border-top-color: alpha(#ffffff, 0.72);"
  "  border-left-color: alpha(#ffffff, 0.60);"
  "  border-right-color: alpha(#5b6672, 0.42);"
  "  border-bottom-color: alpha(#5b6672, 0.42);"
  "}"
  ".mwb-clockbtn .mwb-clocks {"
  "  color: inherit;"
  "}"
  ".mwb-hbox {"
  "  background: transparent;"
  "}"
  ".mwb-status-group {"
  "  padding: 0 3px;"
  "  border: 1px solid alpha(#000000, 0.45);"
  "  border-radius: 4px;"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.35);"
  "}"
  ".mwb-title {"
  "  font-weight: 700;"
  "  padding: 0 6px;"
  "  min-height: 24px;"
  "}"
  ".mwb-title.mwb-title-active {"
  "  text-shadow: none;"
  "}"
  ".mwb-appmenu-item {"
  "  padding: 6px 22px 6px 12px;"
  "}"
  ".mwb-appmenu-item:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-menu-workbench { min-width: 220px; }"
  ".mwb-menu-ambient { min-width: 250px; }"
  ".mwb-menu-icons { min-width: 210px; }"
  ".mwb-menu-disk { min-width: 230px; }"
  ".mwb-menu-applications { min-width: 280px; }"
  /* ---- CLASSIC theme (original Ambient dark-blue) ---- */
  ".mwb-bar.mwb-theme-classic, .mwb-theme-classic.mwb-bar, .mwb-theme-classic .mwb-bar, .mwb-plugin.mwb-theme-classic .mwb-bar, .mwb-plugin.mwb-theme-classic {"
  "  background-image: linear-gradient(to bottom,"
  "    #2c3f5c 0%, #253650 35%, #1c2a40 100%);"
  "  background-color: #1c2a40;"
  "  border: none;"
  "  border-bottom: 1px solid alpha(#000000, 0.45);"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-classic .mwb-button,"
  ".mwb-theme-classic .mwb-volbutton,"
  ".mwb-theme-classic .mwb-clockbtn,"
  ".mwb-theme-classic .mwb-screenbar-pill {"
  "  color: #e6edf5;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-classic .mwb-button:hover {"
  "  background-color: alpha(#4a7fb8, 0.35);"
  "  background-image: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-volbutton:hover,"
  ".mwb-theme-classic .mwb-clockbtn:hover,"
  ".mwb-theme-classic .mwb-screenbar-pill:hover {"
  "  background-color: alpha(#4a7fb8, 0.35);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-button:active, .mwb-theme-classic .mwb-button.open {"
  "  background-color: alpha(#2b5588, 0.60);"
  "  background-image: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-volbutton:active,"
  ".mwb-theme-classic .mwb-clockbtn:active,"
  ".mwb-theme-classic .mwb-screenbar-pill:active {"
  "  background-color: alpha(#2b5588, 0.60);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-clocks {"
  "  color: #dbe6f2;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-classic .mwb-screenbar-item,"
  ".mwb-theme-classic .mwb-title {"
  "  color: #aebfd4;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-classic .mwb-title-active {"
  "  color: #eaf3ff;"
  "}"
  ".mwb-theme-classic .mwb-vgauge-label {"
  "  color: #e6edf5;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "  font-weight: 700;"
  "}"
  ".mwb-theme-classic .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #0a1526 0%, #13203a 100%);"
  "  border: 1px solid alpha(#000000, 0.8);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7), 0 0 0 1px alpha(#ffffff, 0.05);"
  "}"
  ".mwb-theme-classic .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#ffffff, 0.0) 0%, alpha(#ffffff, 0.35) 50%, alpha(#ffffff, 0.0) 100%);"
  "}"
  ".mwb-theme-classic .mwb-screenbar-divider,"
  ".mwb-theme-dark .mwb-screenbar-divider {"
  "  background: alpha(#ffffff, 0.20);"
  "}"
  ".mwb-theme-classic.mwb-menu {"
  "  background-color: rgba(28, 42, 64, 0.90);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.55);"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#6ba3d9, 0.75) 0%, alpha(#3a72ad, 0.75) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem:disabled {"
  "  color: alpha(#dbe6f2, 0.4);"
  "}"
  ".mwb-theme-classic.mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.10);"
  "}"
  ".mwb-theme-classic.mwb-popup {"
  "  background-image: linear-gradient(to bottom, rgba(44, 63, 92, 0.90) 0%, rgba(28, 42, 64, 0.90) 100%);"
  "  background-color: rgba(28, 42, 64, 0.90);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  box-shadow: 0 10px 28px alpha(#000000, 0.65);"
  "}"
  ".mwb-theme-classic.mwb-popup label,"
  ".mwb-theme-classic.mwb-popup calendar {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-theme-classic .mwb-pop-title {"
  "  color: #ffffff;"
  "  text-shadow: 0 1px 2px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-classic .mwb-pop-section-hdr {"
  "  color: #8cb6e2;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-badge-vol {"
  "  background-color: alpha(#112238, 0.85);"
  "  color: #72bbfd;"
  "  border: 1px solid alpha(#6ba3d9, 0.4);"
  "}"
  ".mwb-theme-classic .mwb-badge-playing {"
  "  background-color: alpha(#1a4d2e, 0.85);"
  "  color: #6ee7b7;"
  "  border: 1px solid alpha(#34d399, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-vol-card, .mwb-theme-classic .mwb-notify-card, .mwb-theme-classic.mwb-popup .mwb-vol-card {"
  "  background: transparent;"
  "  border: none;"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-classic.mwb-settings, .mwb-theme-classic .mwb-settings, .mwb-theme-classic.mwb-settings stack, .mwb-theme-classic.mwb-settings .stack {"
  "  background-color: #1c2a40;"
  "  color: #e6edf5;"
  "}"
  ".mwb-theme-classic.mwb-settings list, .mwb-theme-classic.mwb-settings row {"
  "  background-color: #141f30;"
  "  color: #e6edf5;"
  "}"
  ".mwb-theme-classic .mwb-playing-card {"
  "  background-image: linear-gradient(135deg, alpha(#213a60, 0.85) 0%, alpha(#102138, 0.95) 100%);"
  "  border: 1px solid alpha(#6ba3d9, 0.45);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.18), 0 4px 14px alpha(#000000, 0.5);"
  "}"
  ".mwb-theme-classic .mwb-playing-art-frame {"
  "  background-color: #0c1726;"
  "  border: 1px solid alpha(#6ba3d9, 0.35);"
  "  box-shadow: 0 2px 6px alpha(#000000, 0.5);"
  "}"
  ".mwb-theme-classic .mwb-playing-title {"
  "  color: #ffffff;"
  "  text-shadow: 0 1px 2px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-classic .mwb-playing-artist {"
  "  color: #b5d5f7;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-media-btn {"
  "  background-color: alpha(#ffffff, 0.08);"
  "  border: 1px solid alpha(#ffffff, 0.15);"
  "  color: #dbe6f2;"
  "}"
  ".mwb-theme-classic .mwb-media-btn:hover {"
  "  background-color: alpha(#6ba3d9, 0.4);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-media-play-btn {"
  "  background-image: linear-gradient(to bottom, #5ba4ef 0%, #2b70c4 100%);"
  "  border: 1px solid #7dc2ff;"
  "  color: #ffffff;"
  "  box-shadow: 0 2px 8px alpha(#1a4d8c, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-media-play-btn:hover {"
  "  background-image: linear-gradient(to bottom, #72bbfd 0%, #3685d6 100%);"
  "}"
  ".mwb-theme-classic .mwb-streams-card {"
  "  background-color: alpha(#0e1929, 0.65);"
  "  border: 1px solid alpha(#4a7fb8, 0.3);"
  "}"
  ".mwb-theme-classic .mwb-stream-label {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-theme-classic .mwb-stream-empty {"
  "  color: #728ca8;"
  "}"
  ".mwb-theme-classic .mwb-mixer-btn {"
  "  background-image: linear-gradient(to bottom, alpha(#2d4363, 0.8) 0%, alpha(#1a2a42, 0.9) 100%);"
  "  border: 1px solid alpha(#6ba3d9, 0.35);"
  "  color: #e6edf5;"
  "}"
  ".mwb-theme-classic .mwb-mixer-btn:hover {"
  "  background-image: linear-gradient(to bottom, alpha(#4a7fb8, 0.8) 0%, alpha(#2d5b8f, 0.9) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-vol-scale trough {"
  "  background-color: #0c1624;"
  "  border: 1px solid #233752;"
  "  box-shadow: inset 0 1px 2px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-vol-scale highlight {"
  "  background-image: linear-gradient(to bottom, #72bbfd 0%, #3685d6 60%, #1e5fa3 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.3);"
  "}"
  ".mwb-theme-classic .mwb-mic-scale highlight {"
  "  background-image: linear-gradient(to bottom, #ffd166 0%, #f0932b 60%, #b85d0d 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.3);"
  "}"
  ".mwb-theme-classic .mwb-vol-scale slider {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #bddcf7 100%);"
  "  border: 1px solid #1c324e;"
  "  box-shadow: 0 2px 5px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-vol-scale slider:hover {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #e0f0ff 100%);"
  "  box-shadow: 0 0 6px alpha(#72bbfd, 0.8), 0 2px 5px alpha(#000000, 0.6);"
  "}"
  /* ---- DARK theme (sleek near-black) ---- */
  ".mwb-bar.mwb-theme-dark, .mwb-theme-dark.mwb-bar, .mwb-theme-dark .mwb-bar, .mwb-plugin.mwb-theme-dark .mwb-bar, .mwb-plugin.mwb-theme-dark {"
  "  background-image: linear-gradient(to bottom,"
  "    #1c2430 0%, #141a24 45%, #0d121a 100%);"
  "  background-color: #0d121a;"
  "  border: none;"
  "  border-bottom: 1px solid alpha(#000000, 0.6);"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-dark .mwb-button,"
  ".mwb-theme-dark .mwb-volbutton,"
  ".mwb-theme-dark .mwb-clockbtn,"
  ".mwb-theme-dark .mwb-screenbar-pill {"
  "  color: #cfd8e3;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-dark .mwb-button:hover {"
  "  background-color: alpha(#3a5f8a, 0.35);"
  "  background-image: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-volbutton:hover,"
  ".mwb-theme-dark .mwb-clockbtn:hover,"
  ".mwb-theme-dark .mwb-screenbar-pill:hover {"
  "  background-color: alpha(#3a5f8a, 0.35);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-button:active, .mwb-theme-dark .mwb-button.open {"
  "  background-color: alpha(#1a3a5c, 0.60);"
  "  background-image: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-volbutton:active,"
  ".mwb-theme-dark .mwb-clockbtn:active,"
  ".mwb-theme-dark .mwb-screenbar-pill:active {"
  "  background-color: alpha(#1a3a5c, 0.60);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-clocks {"
  "  color: #c9d4e0;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-dark .mwb-screenbar-item,"
  ".mwb-theme-dark .mwb-title {"
  "  color: #94a3b8;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-dark .mwb-title-active {"
  "  color: #e4eef8;"
  "}"
  ".mwb-theme-dark .mwb-vgauge-label {"
  "  color: #e0e6ed;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.8);"
  "  font-weight: 700;"
  "}"
  ".mwb-theme-dark .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #05080d 0%, #0b121c 100%);"
  "  border: 1px solid alpha(#000000, 0.9);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.8), 0 0 0 1px alpha(#ffffff, 0.04);"
  "}"
  ".mwb-theme-dark .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#ffffff, 0.0) 0%, alpha(#ffffff, 0.22) 50%, alpha(#ffffff, 0.0) 100%);"
  "}"
  ".mwb-theme-dark.mwb-menu {"
  "  background-color: rgba(12, 17, 25, 0.90);"
  "  color: #c9d4e0;"
  "  border: 1px solid #000000;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-dark.mwb-menu > menuitem {"
  "  color: #c9d4e0;"
  "}"
  ".mwb-theme-dark.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#4a8fd4, 0.8) 0%, alpha(#2c5f96, 0.8) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark.mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.08);"
  "}"
  ".mwb-theme-dark.mwb-popup {"
  "  background-image: linear-gradient(to bottom, rgba(26, 32, 44, 0.90) 0%, rgba(12, 17, 25, 0.90) 100%);"
  "  background-color: rgba(12, 17, 25, 0.90);"
  "  color: #c9d4e0;"
  "  border: 1px solid #000000;"
  "  box-shadow: 0 10px 28px alpha(#000000, 0.75);"
  "}"
  ".mwb-theme-dark.mwb-popup label,"
  ".mwb-theme-dark.mwb-popup calendar {"
  "  color: #c9d4e0;"
  "}"
  ".mwb-theme-dark .mwb-pop-title {"
  "  color: #ffffff;"
  "  text-shadow: 0 1px 2px alpha(#000000, 0.9);"
  "}"
  ".mwb-theme-dark .mwb-pop-section-hdr {"
  "  color: #71839b;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-badge-vol {"
  "  background-color: alpha(#090d14, 0.9);"
  "  color: #60a5fa;"
  "  border: 1px solid alpha(#3b82f6, 0.4);"
  "}"
  ".mwb-theme-dark .mwb-badge-playing {"
  "  background-color: alpha(#052e16, 0.85);"
  "  color: #4ade80;"
  "  border: 1px solid alpha(#22c55e, 0.5);"
  "}"
  ".mwb-theme-dark .mwb-vol-card, .mwb-theme-dark .mwb-notify-card, .mwb-theme-dark.mwb-popup .mwb-vol-card {"
  "  background: transparent;"
  "  border: none;"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-dark.mwb-settings, .mwb-theme-dark .mwb-settings, .mwb-theme-dark.mwb-settings stack, .mwb-theme-dark.mwb-settings .stack {"
  "  background-color: #0d121a;"
  "  color: #cfd8e3;"
  "}"
  ".mwb-theme-dark.mwb-settings list, .mwb-theme-dark.mwb-settings row {"
  "  background-color: #080c12;"
  "  color: #cfd8e3;"
  "}"
  ".mwb-theme-dark .mwb-playing-card {"
  "  background-image: linear-gradient(135deg, alpha(#1f293a, 0.9) 0%, alpha(#101520, 0.95) 100%);"
  "  border: 1px solid alpha(#475569, 0.5);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.1), 0 4px 14px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-dark .mwb-playing-art-frame {"
  "  background-color: #06090e;"
  "  border: 1px solid alpha(#475569, 0.4);"
  "  box-shadow: 0 2px 6px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-dark .mwb-playing-title {"
  "  color: #ffffff;"
  "  text-shadow: 0 1px 2px alpha(#000000, 0.9);"
  "}"
  ".mwb-theme-dark .mwb-playing-artist {"
  "  color: #94a3b8;"
  "}"
  ".mwb-theme-dark .mwb-media-btn {"
  "  background-color: alpha(#ffffff, 0.06);"
  "  border: 1px solid alpha(#ffffff, 0.1);"
  "  color: #cbd5e1;"
  "}"
  ".mwb-theme-dark .mwb-media-btn:hover {"
  "  background-color: alpha(#3b82f6, 0.35);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-media-play-btn {"
  "  background-image: linear-gradient(to bottom, #3b82f6 0%, #1d4ed8 100%);"
  "  border: 1px solid #60a5fa;"
  "  color: #ffffff;"
  "  box-shadow: 0 2px 8px alpha(#1e40af, 0.6);"
  "}"
  ".mwb-theme-dark .mwb-media-play-btn:hover {"
  "  background-image: linear-gradient(to bottom, #60a5fa 0%, #2563eb 100%);"
  "}"
  ".mwb-theme-dark .mwb-streams-card {"
  "  background-color: alpha(#070a0f, 0.7);"
  "  border: 1px solid alpha(#252e3d, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-stream-label {"
  "  color: #cbd5e1;"
  "}"
  ".mwb-theme-dark .mwb-stream-empty {"
  "  color: #64748b;"
  "}"
  ".mwb-theme-dark .mwb-mixer-btn {"
  "  background-image: linear-gradient(to bottom, alpha(#1e293b, 0.85) 0%, alpha(#0f172a, 0.95) 100%);"
  "  border: 1px solid alpha(#475569, 0.6);"
  "  color: #e2e8f0;"
  "}"
  ".mwb-theme-dark .mwb-mixer-btn:hover {"
  "  background-image: linear-gradient(to bottom, alpha(#3b82f6, 0.5) 0%, alpha(#1d4ed8, 0.6) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-vol-scale trough {"
  "  background-color: #080b10;"
  "  border: 1px solid #1e2634;"
  "  box-shadow: inset 0 1px 2px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-vol-scale highlight {"
  "  background-image: linear-gradient(to bottom, #60a5fa 0%, #3b82f6 60%, #1d4ed8 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.25);"
  "}"
  ".mwb-theme-dark .mwb-mic-scale highlight {"
  "  background-image: linear-gradient(to bottom, #fde047 0%, #eab308 60%, #a16207 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.25);"
  "}"
  ".mwb-theme-dark .mwb-vol-scale slider {"
  "  background-image: linear-gradient(to bottom, #f8fafc 0%, #cbd5e1 100%);"
  "  border: 1px solid #0f172a;"
  "  box-shadow: 0 2px 5px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-dark .mwb-vol-scale slider:hover {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #e2e8f0 100%);"
  "  box-shadow: 0 0 6px alpha(#60a5fa, 0.8), 0 2px 5px alpha(#000000, 0.7);"
  "}"
  /* ---- LIGHT theme (silver / classic Workbench metal) ---- */
  ".mwb-bar.mwb-theme-light, .mwb-theme-light.mwb-bar, .mwb-theme-light .mwb-bar, .mwb-plugin.mwb-theme-light .mwb-bar, .mwb-plugin.mwb-theme-light {"
  "  background-image: linear-gradient(to bottom,"
  "    #f2f4f7 0%, #d9dee5 45%, #b8c0ca 100%);"
  "  background-color: #cdd4dc;"
  "  border: none;"
  "  border-bottom: 1px solid alpha(#6a7280, 0.70);"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-light .mwb-button,"
  ".mwb-theme-light .mwb-volbutton,"
  ".mwb-theme-light .mwb-clockbtn,"
  ".mwb-theme-light .mwb-screenbar-pill {"
  "  color: #2b3440;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-light .mwb-button:hover {"
  "  background-color: alpha(#000000, 0.08);"
  "  background-image: none;"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-volbutton:hover,"
  ".mwb-theme-light .mwb-clockbtn:hover,"
  ".mwb-theme-light .mwb-screenbar-pill:hover {"
  "  background-color: alpha(#000000, 0.08);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #0f172a;"
  "}"
  ".mwb-theme-light .mwb-button:active, .mwb-theme-light .mwb-button.open {"
  "  background-color: alpha(#000000, 0.16);"
  "  background-image: none;"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-volbutton:active,"
  ".mwb-theme-light .mwb-clockbtn:active,"
  ".mwb-theme-light .mwb-screenbar-pill:active {"
  "  background-color: alpha(#000000, 0.16);"
  "  background-image: none;"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: #0f172a;"
  "}"
  ".mwb-theme-light .mwb-clocks {"
  "  color: #2b3440;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-light .mwb-screenbar-item,"
  ".mwb-theme-light .mwb-title {"
  "  color: #5b6672;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-light .mwb-title-active {"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-vgauge-label {"
  "  color: #2b3440;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.6);"
  "  font-weight: 700;"
  "}"
  ".mwb-theme-light .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #9aa4b0 0%, #c3ccd5 100%);"
  "  border: 1px solid alpha(#5b6672, 0.7);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.8), 0 0 0 1px alpha(#6a7480, 0.3);"
  "}"
  ".mwb-theme-light .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#000000, 0.0) 0%, alpha(#5b6672, 0.45) 50%, alpha(#000000, 0.0) 100%);"
  "}"
  ".mwb-theme-light .mwb-screenbar-divider {"
  "  background: alpha(#5b6672, 0.38);"
  "}"
  ".mwb-theme-classic .mwb-island, .mwb-theme-dark .mwb-island {"
  "  background: alpha(#07111e, 0.42);"
  "  border-top-color: alpha(#ffffff, 0.18);"
  "  border-left-color: alpha(#ffffff, 0.10);"
  "  border-right-color: alpha(#000000, 0.65);"
  "  border-bottom-color: alpha(#000000, 0.65);"
  "}"
  ".mwb-theme-light .mwb-island {"
  "  background: alpha(#f7f9fb, 0.42);"
  "  border-top-color: alpha(#ffffff, 0.85);"
  "  border-left-color: alpha(#ffffff, 0.65);"
  "  border-right-color: alpha(#5b6672, 0.45);"
  "  border-bottom-color: alpha(#5b6672, 0.45);"
  "}"
  ".mwb-theme-light.mwb-menu {"
  "  background-color: rgba(240, 243, 247, 0.95);"
  "  color: #2b3440;"
  "  border: 1px solid #87909b;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.25);"
  "}"
  ".mwb-theme-light.mwb-menu > menuitem {"
  "  color: #2b3440;"
  "}"
  ".mwb-theme-light.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    #5a87c4 0%, #3f6da8 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-light.mwb-menu > separator {"
  "  background: alpha(#2b3440, 0.12);"
  "}"
  ".mwb-theme-light.mwb-popup {"
  "  background-image: linear-gradient(to bottom, rgba(255, 255, 255, 0.96) 0%, rgba(235, 240, 246, 0.96) 100%);"
  "  background-color: rgba(240, 243, 247, 0.96);"
  "  color: #1e293b;"
  "  border: 1px solid #bcc6d2;"
  "  box-shadow: 0 10px 28px alpha(#000000, 0.20);"
  "}"
  ".mwb-theme-light.mwb-popup label,"
  ".mwb-theme-light.mwb-popup calendar {"
  "  color: #1e293b;"
  "}"
  ".mwb-theme-light .mwb-pop-title {"
  "  color: #0f172a;"
  "}"
  ".mwb-theme-light .mwb-pop-section-hdr {"
  "  color: #556579;"
  "}"
  ".mwb-theme-light .mwb-badge-vol {"
  "  background-color: alpha(#e2e8f0, 0.9);"
  "  color: #1d4ed8;"
  "  border: 1px solid alpha(#93c5fd, 0.8);"
  "}"
  ".mwb-theme-light .mwb-badge-playing {"
  "  background-color: alpha(#dcfce7, 0.9);"
  "  color: #15803d;"
  "  border: 1px solid alpha(#86efac, 0.8);"
  "}"
  ".mwb-theme-light .mwb-vol-card, .mwb-theme-light .mwb-notify-card, .mwb-theme-light.mwb-popup .mwb-vol-card {"
  "  background: transparent;"
  "  border: none;"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-light.mwb-settings, .mwb-theme-light .mwb-settings, .mwb-theme-light.mwb-settings stack, .mwb-theme-light.mwb-settings .stack {"
  "  background-color: #e6ebf2;"
  "  color: #2b3440;"
  "}"
  ".mwb-theme-light.mwb-settings list, .mwb-theme-light.mwb-settings row {"
  "  background-color: #f7f9fb;"
  "  color: #2b3440;"
  "}"
  ".mwb-theme-light .mwb-playing-card {"
  "  background-image: linear-gradient(135deg, alpha(#ffffff, 0.95) 0%, alpha(#e8eef5, 0.95) 100%);"
  "  border: 1px solid alpha(#94a3b8, 0.6);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 1.0), 0 4px 10px alpha(#000000, 0.08);"
  "}"
  ".mwb-theme-light .mwb-playing-art-frame {"
  "  background-color: #f1f5f9;"
  "  border: 1px solid alpha(#cbd5e1, 0.9);"
  "  box-shadow: 0 2px 4px alpha(#000000, 0.08);"
  "}"
  ".mwb-theme-light .mwb-playing-title {"
  "  color: #0f172a;"
  "}"
  ".mwb-theme-light .mwb-playing-artist {"
  "  color: #475569;"
  "}"
  ".mwb-theme-light .mwb-media-btn {"
  "  background-color: alpha(#000000, 0.05);"
  "  border: 1px solid alpha(#000000, 0.1);"
  "  color: #334155;"
  "}"
  ".mwb-theme-light .mwb-media-btn:hover {"
  "  background-color: alpha(#3b82f6, 0.18);"
  "  color: #0f172a;"
  "}"
  ".mwb-theme-light .mwb-media-play-btn {"
  "  background-image: linear-gradient(to bottom, #3b82f6 0%, #2563eb 100%);"
  "  border: 1px solid #1d4ed8;"
  "  color: #ffffff;"
  "  box-shadow: 0 2px 6px alpha(#3b82f6, 0.4);"
  "}"
  ".mwb-theme-light .mwb-media-play-btn:hover {"
  "  background-image: linear-gradient(to bottom, #60a5fa 0%, #3b82f6 100%);"
  "}"
  ".mwb-theme-light .mwb-streams-card {"
  "  background-color: alpha(#ffffff, 0.8);"
  "  border: 1px solid alpha(#cbd5e1, 0.9);"
  "}"
  ".mwb-theme-light .mwb-stream-label {"
  "  color: #1e293b;"
  "}"
  ".mwb-theme-light .mwb-stream-empty {"
  "  color: #64748b;"
  "}"
  ".mwb-theme-light .mwb-mixer-btn {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #e8edf3 100%);"
  "  border: 1px solid #cbd5e1;"
  "  color: #1e293b;"
  "}"
  ".mwb-theme-light .mwb-mixer-btn:hover {"
  "  background-image: linear-gradient(to bottom, #f0f7ff 0%, #dbeafe 100%);"
  "  border-color: #93c5fd;"
  "  color: #1d4ed8;"
  "}"
  ".mwb-theme-light .mwb-vol-scale trough {"
  "  background-color: #cbd5e1;"
  "  border: 1px solid #94a3b8;"
  "  box-shadow: inset 0 1px 2px alpha(#000000, 0.15);"
  "}"
  ".mwb-theme-light .mwb-vol-scale highlight {"
  "  background-image: linear-gradient(to bottom, #60a5fa 0%, #3b82f6 60%, #2563eb 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.4);"
  "}"
  ".mwb-theme-light .mwb-mic-scale highlight {"
  "  background-image: linear-gradient(to bottom, #fde047 0%, #eab308 60%, #ca8a04 100%);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.4);"
  "}"
  ".mwb-theme-light .mwb-vol-scale slider {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #e2e8f0 100%);"
  "  border: 1px solid #64748b;"
  "  box-shadow: 0 1px 4px alpha(#000000, 0.25);"
  "}"
  ".mwb-theme-light .mwb-vol-scale slider:hover {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #f1f5f9 100%);"
  "  box-shadow: 0 0 5px alpha(#3b82f6, 0.6), 0 1px 4px alpha(#000000, 0.25);"
  "}"
  /* ================================================================ */
  /* SYSTEM THEME (NATIVE GTK & XFCE4 PANEL INTEGRATION)               */
  /* ================================================================ */
  ".mwb-bar.mwb-theme-system, .mwb-theme-system.mwb-bar, .mwb-theme-system .mwb-bar, .mwb-plugin.mwb-theme-system .mwb-bar, .mwb-plugin.mwb-theme-system {"
  "  background: transparent !important;"
  "  background-color: transparent !important;"
  "  background-image: none !important;"
  "  border: none !important;"
  "  box-shadow: none !important;"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-button, .mwb-theme-system .mwb-volbutton, .mwb-theme-system .mwb-clockbtn, .mwb-theme-system .mwb-screenbar-pill, .mwb-theme-system .mwb-island, .mwb-theme-system .mwb-gaugebox, .mwb-theme-system .mwb-gauge-island, .mwb-theme-system .nm-panel-button {"
  "  background-color: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  color: @theme_fg_color;"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-system .mwb-button:hover, .mwb-theme-system .mwb-volbutton:hover, .mwb-theme-system .mwb-clockbtn:hover, .mwb-theme-system .mwb-screenbar-pill:hover, .mwb-theme-system .nm-panel-button:hover, .mwb-theme-system .nm-panel-button.open {"
  "  background-color: alpha(@theme_selected_bg_color, 0.25);"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: @theme_selected_fg_color;"
  "}"
  ".mwb-theme-system .mwb-button:active, .mwb-theme-system .mwb-button.open, .mwb-theme-system .mwb-volbutton:active, .mwb-theme-system .mwb-clockbtn:active, .mwb-theme-system .mwb-screenbar-pill:active {"
  "  background-color: alpha(@theme_selected_bg_color, 0.50);"
  "  border-color: transparent;"
  "  box-shadow: none;"
  "  color: @theme_selected_fg_color;"
  "}"
  ".mwb-theme-system .mwb-clocks, .mwb-theme-system .mwb-title, .mwb-theme-system .mwb-screenbar-item {"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-title-active {"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-vgauge-label {"
  "  color: @theme_fg_color;"
  "  font-weight: 700;"
  "}"
  ".mwb-theme-system .mwb-lamp {"
  "  background-color: transparent;"
  "  border: none;"
  "}"
  ".mwb-theme-system.mwb-menu, .mwb-theme-system .mwb-menu, menu.mwb-theme-system {"
  "  background-color: @theme_bg_color;"
  "  color: @theme_fg_color;"
  "  border: 1px solid alpha(@theme_fg_color, 0.15);"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.40);"
  "}"
  ".mwb-theme-system.mwb-menu > menuitem, .mwb-theme-system .mwb-appmenu-item, .mwb-theme-system.mwb-menu menuitem {"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system.mwb-menu > menuitem:hover, .mwb-theme-system .mwb-appmenu-item:hover, .mwb-theme-system.mwb-menu menuitem:hover {"
  "  background-color: @theme_selected_bg_color;"
  "  color: @theme_selected_fg_color;"
  "}"
  ".mwb-theme-system.mwb-menu > menuitem:disabled, .mwb-theme-system.mwb-menu menuitem:disabled {"
  "  color: alpha(@theme_fg_color, 0.35);"
  "}"
  ".mwb-theme-system.mwb-menu > separator, .mwb-theme-system.mwb-menu separator {"
  "  background: alpha(@theme_fg_color, 0.12);"
  "}"
  ".mwb-theme-system.mwb-popup, .mwb-theme-system.mwb-vol-popup, .mwb-theme-system .mwb-vol-popup {"
  "  background-color: @theme_bg_color;"
  "  color: @theme_fg_color;"
  "  border: 1px solid alpha(@theme_fg_color, 0.20);"
  "  box-shadow: 0 10px 28px alpha(#000000, 0.50);"
  "}"
  ".mwb-theme-system.mwb-popup label, .mwb-theme-system.mwb-popup calendar {"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-pop-title {"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-pop-section-hdr {"
  "  color: alpha(@theme_fg_color, 0.70);"
  "}"
  ".mwb-theme-system .mwb-badge-vol, .mwb-theme-system .mwb-vol-badge, .mwb-theme-system .mwb-badge {"
  "  background-color: alpha(@theme_selected_bg_color, 0.20);"
  "  color: @theme_selected_bg_color;"
  "  border: 1px solid alpha(@theme_selected_bg_color, 0.40);"
  "}"
  ".mwb-theme-system .mwb-vol-card, .mwb-theme-system .mwb-notify-card, .mwb-theme-system.mwb-popup .mwb-vol-card {"
  "  background: transparent;"
  "  border: none;"
  "  box-shadow: none;"
  "}"
  ".mwb-theme-system .mwb-media-btn, .mwb-theme-system .mwb-gear-btn, .mwb-theme-system .mwb-notify-dismiss {"
  "  background-color: alpha(@theme_fg_color, 0.08);"
  "  border: 1px solid alpha(@theme_fg_color, 0.15);"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-media-btn:hover, .mwb-theme-system .mwb-gear-btn:hover, .mwb-theme-system .mwb-notify-dismiss:hover {"
  "  background-color: alpha(@theme_selected_bg_color, 0.25);"
  "  border-color: alpha(@theme_selected_bg_color, 0.50);"
  "  color: @theme_selected_fg_color;"
  "}"
  ".mwb-theme-system .mwb-media-play-btn {"
  "  background-color: @theme_selected_bg_color;"
  "  color: @theme_selected_fg_color;"
  "  border: 1px solid alpha(@theme_selected_fg_color, 0.30);"
  "}"
  ".mwb-theme-system .mwb-vol-scale trough {"
  "  background-color: alpha(@theme_fg_color, 0.15);"
  "  border: 1px solid alpha(@theme_fg_color, 0.20);"
  "}"
  ".mwb-theme-system .mwb-vol-scale highlight {"
  "  background-color: @theme_selected_bg_color;"
  "}"
  ".mwb-theme-system .mwb-mic-scale highlight {"
  "  background-color: alpha(@theme_selected_bg_color, 0.85);"
  "}"
  ".mwb-theme-system .mwb-vol-scale slider {"
  "  background-color: @theme_bg_color;"
  "  border: 1px solid alpha(@theme_fg_color, 0.35);"
  "  box-shadow: 0 1px 3px alpha(#000000, 0.25);"
  "}"
  ".mwb-theme-system .mwb-mixer-btn {"
  "  background-color: alpha(@theme_fg_color, 0.08);"
  "  border: 1px solid alpha(@theme_fg_color, 0.15);"
  "  color: @theme_fg_color;"
  "}"
  ".mwb-theme-system .mwb-mixer-btn:hover {"
  "  background-color: alpha(@theme_selected_bg_color, 0.20);"
  "  border-color: alpha(@theme_selected_bg_color, 0.40);"
  "  color: @theme_selected_fg_color;"
  "}"
  /* lamp colors (shared traffic-light diodes) */
  ".mwb-lamp.net {"
  "  background-image: linear-gradient(to bottom, #b23a3a 0%, #6b1b1b 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7), 0 0 3px alpha(#b23a3a, 0.5);"
  "}"
  ".mwb-lamp.disk {"
  "  background-image: linear-gradient(to bottom, #7a5a20 0%, #3a2c0d 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7);"
  "}"
  ".mwb-lamp.active-net,"
  ".mwb-lamp.active-disk {"
  "  background-image: linear-gradient(to bottom,"
  "    #fff3a0 0%, #f0a32d 60%, #b87215 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.5),"
  "    0 0 6px alpha(#f0a32d, 0.9), 0 0 12px alpha(#f0a32d, 0.4);"
  "}"
  ".mwb-lamp.active-net-high {"
  "  background-image: linear-gradient(to bottom,"
  "    #9fe3ff 0%, #37b0f0 60%, #1570b8 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.5),"
  "    0 0 6px alpha(#37b0f0, 0.9), 0 0 12px alpha(#37b0f0, 0.4);"
  "}"
  /* ---- stronger selected / focused states ---- */
  ".mwb-button:focus, .mwb-volbutton:focus, .mwb-clockbtn:focus,"
  ".mwb-button:active, .mwb-volbutton:active, .mwb-clockbtn:active {"
  "  outline: none;"
  "}"
  ".mwb-menu > menuitem:hover,"
  ".mwb-menu > menuitem:selected {"
  "  box-shadow: none;"
  "}"
  /* ---- Embedded xfce4-networkmanager button — match the screenbar ---- */
  ".nm-panel-button {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  padding: 0 4px;"
  "  min-height: 24px;"
  "}"
  ".mwb-theme-classic .nm-panel-button,"
  ".mwb-theme-dark .nm-panel-button {"
  "  color: #e6edf5;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-light .nm-panel-button {"
  "  color: #2b3440;"
  "  text-shadow: none;"
  "}"
  ".mwb-theme-classic .nm-panel-button:hover,"
  ".mwb-theme-classic .nm-panel-button.open,"
  ".mwb-theme-dark .nm-panel-button:hover,"
  ".mwb-theme-dark .nm-panel-button.open {"
  "  background-color: alpha(#4a7fb8, 0.5);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-light .nm-panel-button:hover,"
  ".mwb-theme-light .nm-panel-button.open {"
  "  background-color: alpha(#b9c4d0, 0.65);"
  "  color: #101722;"
  "}"
  /* ---- Workbench override: pin down every widget so the desktop theme
   *      cannot leak through. Applied to the bar, menus and popups when
   *      "Override GTK theme" is enabled. ---- */
  ".mwb-override.mwb-menu > menuitem {"
  "  min-height: 24px;"
  "  padding: 2px 8px;"
  "}"
  ".mwb-override .mwb-menu > separator {"
  "  min-height: 1px;"
  "}"
  ".mwb-override.mwb-popup calendar {"
  "  background: transparent;"
  "}"
  ".mwb-override .mwb-popup scale trough {"
  "  border-radius: 9999px;"
  "}"
  ".mwb-override .mwb-gaugebox {"
  "  border-radius: 8px;"
  "}"
  ".mwb-override .mwb-volbutton,"
  ".mwb-override .mwb-clockbtn {"
  "  border-radius: 5px;"
  "}"
  ".mwb-override .mwb-vol-card,"
  ".mwb-override .mwb-streams-card {"
  "  border-radius: 8px;"
  "}"
  ".mwb-override .mwb-playing-card {"
  "  border-radius: 10px;"
  "}"
  ".mwb-override .mwb-playing-art-frame {"
  "  border-radius: 8px;"
  "}"
  ".mwb-override .mwb-media-btn,"
  ".mwb-override .mwb-mixer-btn {"
  "  border-radius: 6px;"
  "}"
  ".mwb-override .mwb-media-play-btn {"
  "  border-radius: 14px;"
  "}"
  ".mwb-override .mwb-button:hover,"
  ".mwb-override .mwb-volbutton:hover,"
  ".mwb-override .mwb-clockbtn:hover {"
  "  box-shadow: inset 0 0 0 1px alpha(#6ba3d9, 0.45);"
  "}"
  /* ---- Clear / Transparent background mode ---- */
  ".mwb-clear-bg, .mwb-clear-bg .mwb-bar, .mwb-bar.mwb-clear-bg, .mwb-theme-classic.mwb-clear-bg, .mwb-theme-dark.mwb-clear-bg, .mwb-theme-light.mwb-clear-bg, .mwb-plugin.mwb-clear-bg, .mwb-theme-classic .mwb-bar.mwb-clear-bg, .mwb-theme-dark .mwb-bar.mwb-clear-bg, .mwb-theme-light .mwb-bar.mwb-clear-bg {"
  "  background: transparent !important;"
  "  background-image: none !important;"
  "  background-color: transparent !important;"
  "  border: none !important;"
  "  border-top: none !important;"
  "  border-bottom: none !important;"
  "  border-left: none !important;"
  "  border-right: none !important;"
  "  box-shadow: none !important;"
  "}"
  ".mwb-clear-bg .mwb-island, .mwb-clear-bg.mwb-island, .mwb-bar.mwb-clear-bg .mwb-island, .mwb-clear-bg .mwb-screenbar-pill, .mwb-clear-bg .mwb-volbutton, .mwb-clear-bg .mwb-clockbtn, .mwb-clear-bg .mwb-gaugebox, .mwb-clear-bg .mwb-gauge-island {"
  "  background: alpha(#000000, 0.40) !important;"
  "  border: 1px solid alpha(#ffffff, 0.20) !important;"
  "  border-radius: 4px !important;"
  "  box-shadow: 0 1px 3px alpha(#000000, 0.50), inset 0 1px 0 alpha(#ffffff, 0.08) !important;"
  "}"
  ".mwb-clear-bg .mwb-volbutton:hover, .mwb-clear-bg .mwb-clockbtn:hover, .mwb-clear-bg .mwb-screenbar-pill:hover, .mwb-clear-bg .mwb-button:hover {"
  "  background: alpha(#000000, 0.60) !important;"
  "  border-color: alpha(#ffffff, 0.40) !important;"
  "}"
  ".mwb-clear-bg .mwb-button, .mwb-clear-bg .mwb-volbutton, .mwb-clear-bg .mwb-clockbtn, .mwb-clear-bg .mwb-clocks, .mwb-clear-bg .mwb-title, .mwb-clear-bg .mwb-screenbar-item, .mwb-clear-bg .mwb-screenbar-pill {"
  "  color: #ffffff !important;"
  "  text-shadow: 0 1px 2px alpha(#000000, 0.95), 0 0 1px #000000 !important;"
  "}"
  ".mwb-theme-light .mwb-clear-bg .mwb-island, .mwb-theme-light.mwb-clear-bg .mwb-island, .mwb-theme-light .mwb-bar.mwb-clear-bg .mwb-island, .mwb-theme-light .mwb-clear-bg .mwb-screenbar-pill, .mwb-theme-light .mwb-clear-bg .mwb-volbutton, .mwb-theme-light .mwb-clear-bg .mwb-clockbtn, .mwb-theme-light .mwb-clear-bg .mwb-gaugebox, .mwb-theme-light .mwb-clear-bg .mwb-gauge-island {"
  "  background: alpha(#ffffff, 0.50) !important;"
  "  border: 1px solid alpha(#000000, 0.20) !important;"
  "  border-radius: 4px !important;"
  "  box-shadow: 0 1px 3px alpha(#000000, 0.20) !important;"
  "}"
  ".mwb-theme-light .mwb-clear-bg .mwb-volbutton:hover, .mwb-theme-light .mwb-clear-bg .mwb-clockbtn:hover, .mwb-theme-light .mwb-clear-bg .mwb-screenbar-pill:hover, .mwb-theme-light .mwb-clear-bg .mwb-button:hover {"
  "  background: alpha(#ffffff, 0.75) !important;"
  "  border-color: alpha(#000000, 0.35) !important;"
  "}"
  ".mwb-theme-light .mwb-clear-bg .mwb-button, .mwb-theme-light .mwb-clear-bg .mwb-volbutton, .mwb-theme-light .mwb-clear-bg .mwb-clockbtn, .mwb-theme-light .mwb-clear-bg .mwb-clocks, .mwb-theme-light .mwb-clear-bg .mwb-title, .mwb-theme-light .mwb-clear-bg .mwb-screenbar-item, .mwb-theme-light .mwb-clear-bg .mwb-screenbar-pill {"
  "  color: #1e293b !important;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.80) !important;"
  "}"
  ".mwb-clear-bg .mwb-popup, .mwb-clear-bg.mwb-popup, .mwb-clear-bg .mwb-vol-popup, .mwb-clear-bg.mwb-vol-popup, .mwb-clear-bg #mwb-batt-pop, .mwb-clear-bg #mwb-notify-pop, .mwb-clear-bg #mwb-volume-pop, .mwb-clear-bg #mwb-calendar, .mwb-clear-bg #mwb-wifi-pop {"
  "  background-image: linear-gradient(to bottom, #1d2c44 0%, #152236 100%) !important;"
  "  background-color: #152236 !important;"
  "  border: 1px solid #334d73 !important;"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.22), 0 14px 36px alpha(#000000, 0.85) !important;"
  "}"
  ".mwb-clear-bg .mwb-vol-card, .mwb-clear-bg.mwb-popup .mwb-vol-card, .mwb-clear-bg .mwb-notify-card {"
  "  background-color: #0c1828 !important;"
  "  border: 1px solid #233b5c !important;"
  "  box-shadow: inset 0 1px 2px alpha(#000000, 0.55), 0 1px 0 alpha(#ffffff, 0.08) !important;"
  "}"
  ".mwb-theme-light .mwb-clear-bg .mwb-popup, .mwb-theme-light.mwb-clear-bg .mwb-popup, .mwb-theme-light .mwb-clear-bg .mwb-vol-popup, .mwb-theme-light.mwb-clear-bg .mwb-vol-popup, .mwb-theme-light .mwb-clear-bg #mwb-batt-pop, .mwb-theme-light .mwb-clear-bg #mwb-notify-pop, .mwb-theme-light .mwb-clear-bg #mwb-volume-pop, .mwb-theme-light .mwb-clear-bg #mwb-calendar, .mwb-theme-light .mwb-clear-bg #mwb-wifi-pop {"
  "  background-image: linear-gradient(to bottom, #f5f7fa 0%, #e2e7ee 100%) !important;"
  "  background-color: #e2e7ee !important;"
  "  border: 1px solid #8e9aa8 !important;"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.95), 0 14px 36px alpha(#000000, 0.35) !important;"
  "}"
  ".mwb-theme-light .mwb-clear-bg .mwb-vol-card, .mwb-theme-light.mwb-clear-bg.mwb-popup .mwb-vol-card, .mwb-theme-light .mwb-clear-bg .mwb-notify-card {"
  "  background-color: #ffffff !important;"
  "  border: 1px solid #cbd5e1 !important;"
  "  box-shadow: inset 0 1px 2px alpha(#ffffff, 0.8), 0 1px 3px alpha(#000000, 0.08) !important;"
  "}"
  "";

static void
mwb_add_provider_to_all_screens(GtkCssProvider *provider, guint priority)
{
    GdkDisplay *display = gdk_display_get_default();
    if (!display)
        return;
    GdkScreen *screen = gdk_display_get_default_screen(display);
    if (screen)
        gtk_style_context_add_provider_for_screen(screen, GTK_STYLE_PROVIDER(provider), priority);
}

static void
mwb_remove_provider_from_all_screens(GtkCssProvider *provider)
{
    GdkDisplay *display = gdk_display_get_default();
    if (!display)
        return;
    GdkScreen *screen = gdk_display_get_default_screen(display);
    if (screen)
        gtk_style_context_remove_provider_for_screen(screen, GTK_STYLE_PROVIDER(provider));
}

void
mwb_init_css(void)
{
    static gboolean loaded = FALSE;
    if (loaded)
        return;
    loaded = TRUE;

    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_data(provider, MWB_CSS, -1, NULL);
    mwb_add_provider_to_all_screens(provider, GTK_STYLE_PROVIDER_PRIORITY_USER);
    g_object_unref(provider);
}

void
mwb_apply_menu_opacity(MorphosWorkbenchPlugin *mwb)
{
    static GtkCssProvider *provider = NULL;
    gdouble alpha;
    gchar *css;

    /* remove the previous provider so the new opacity actually takes effect */
    if (provider) {
        mwb_remove_provider_from_all_screens(provider);
        g_object_unref(provider);
        provider = NULL;
    }

    provider = gtk_css_provider_new();
    mwb_add_provider_to_all_screens(provider, GTK_STYLE_PROVIDER_PRIORITY_USER + 50);

    alpha = CLAMP(mwb->menu_opacity, 0, 100) / 100.0;
    css = g_strdup_printf(
        "window.popup, window.popup > menu, window.background.popup, window.menu, .mwb-menu-window {\n"
        "  background: transparent !important;\n"
        "  background-color: transparent !important;\n"
        "  background-image: none !important;\n"
        "}\n"
        ".mwb-theme-classic.mwb-menu, .mwb-theme-classic .mwb-menu, menu.mwb-theme-classic, .mwb-theme-classic.mwb-menu-applications, .mwb-theme-classic.mwb-menu-workbench, .mwb-theme-classic.mwb-menu-ambient, .mwb-theme-classic.mwb-menu-icons, .mwb-theme-classic.mwb-menu-disk,\n"
        ".mwb-theme-classic.mwb-popup, .mwb-theme-classic .mwb-popup, .mwb-theme-classic.mwb-vol-popup, .mwb-theme-classic .mwb-vol-popup, window.mwb-theme-classic.mwb-popup, window.mwb-theme-classic.mwb-vol-popup, #mwb-volume-pop, #mwb-calendar, #mwb-notify-pop, #mwb-batt-pop, #mwb-wifi-pop {\n"
        "  background-image: linear-gradient(to bottom, rgba(44, 63, 92, %.3f) 0%%, rgba(28, 42, 64, %.3f) 100%%) !important;\n"
        "  background-color: rgba(28, 42, 64, %.3f) !important;\n"
        "  border: 1px solid #0a1526 !important;\n"
        "  box-shadow: 0 10px 28px rgba(0,0,0,0.65) !important;\n"
        "}\n"
        ".mwb-theme-dark.mwb-menu, .mwb-theme-dark .mwb-menu, menu.mwb-theme-dark, .mwb-theme-dark.mwb-menu-applications, .mwb-theme-dark.mwb-menu-workbench, .mwb-theme-dark.mwb-menu-ambient, .mwb-theme-dark.mwb-menu-icons, .mwb-theme-dark.mwb-menu-disk,\n"
        ".mwb-theme-dark.mwb-popup, .mwb-theme-dark .mwb-popup, .mwb-theme-dark.mwb-vol-popup, .mwb-theme-dark .mwb-vol-popup, window.mwb-theme-dark.mwb-popup, window.mwb-theme-dark.mwb-vol-popup, #mwb-volume-pop, #mwb-calendar, #mwb-notify-pop, #mwb-batt-pop, #mwb-wifi-pop {\n"
        "  background-image: linear-gradient(to bottom, rgba(26, 32, 44, %.3f) 0%%, rgba(12, 17, 25, %.3f) 100%%) !important;\n"
        "  background-color: rgba(12, 17, 25, %.3f) !important;\n"
        "  border: 1px solid #000000 !important;\n"
        "  box-shadow: 0 10px 28px rgba(0,0,0,0.75) !important;\n"
        "}\n"
        ".mwb-theme-light.mwb-menu, .mwb-theme-light .mwb-menu, menu.mwb-theme-light, .mwb-theme-light.mwb-menu-applications, .mwb-theme-light.mwb-menu-workbench, .mwb-theme-light.mwb-menu-ambient, .mwb-theme-light.mwb-menu-icons, .mwb-theme-light.mwb-menu-disk,\n"
        ".mwb-theme-light.mwb-popup, .mwb-theme-light .mwb-popup, .mwb-theme-light.mwb-vol-popup, .mwb-theme-light .mwb-vol-popup, window.mwb-theme-light.mwb-popup, window.mwb-theme-light.mwb-vol-popup, #mwb-volume-pop, #mwb-calendar, #mwb-notify-pop, #mwb-batt-pop, #mwb-wifi-pop {\n"
        "  background-image: linear-gradient(to bottom, rgba(255, 255, 255, %.3f) 0%%, rgba(235, 240, 246, %.3f) 100%%) !important;\n"
        "  background-color: rgba(240, 243, 247, %.3f) !important;\n"
        "  border: 1px solid #bcc6d2 !important;\n"
        "  box-shadow: 0 10px 28px rgba(0,0,0,0.20) !important;\n"
        "}\n"
        ".mwb-theme-system.mwb-menu, .mwb-theme-system .mwb-menu, menu.mwb-theme-system, .mwb-theme-system.mwb-menu-applications, .mwb-theme-system.mwb-menu-workbench, .mwb-theme-system.mwb-menu-ambient, .mwb-theme-system.mwb-menu-icons, .mwb-theme-system.mwb-menu-disk,\n"
        ".mwb-theme-system.mwb-popup, .mwb-theme-system .mwb-popup, .mwb-theme-system.mwb-vol-popup, .mwb-theme-system .mwb-vol-popup, window.mwb-theme-system.mwb-popup, window.mwb-theme-system.mwb-vol-popup, #mwb-volume-pop, #mwb-calendar, #mwb-notify-pop, #mwb-batt-pop, #mwb-wifi-pop {\n"
        "  background-color: alpha(@theme_bg_color, %.3f) !important;\n"
        "  border: 1px solid alpha(@theme_fg_color, 0.20) !important;\n"
        "  box-shadow: 0 10px 28px rgba(0,0,0,0.40) !important;\n"
        "}\n"
        ".mwb-vol-card, .mwb-notify-card, .mwb-streams-card {\n"
        "  background: transparent !important;\n"
        "  background-color: transparent !important;\n"
        "  background-image: none !important;\n"
        "  border: none !important;\n"
        "  box-shadow: none !important;\n"
        "}\n",
        alpha, alpha, alpha,
        alpha, alpha, alpha,
        alpha, alpha, alpha,
        alpha);
    gtk_css_provider_load_from_data(provider, css, -1, NULL);
    g_free(css);
}

void
mwb_theme_widget(MorphosWorkbenchPlugin *mwb, GtkWidget *widget)
{
    static const gchar *classes[MWB_THEME_COUNT] = {
        "mwb-theme-classic", "mwb-theme-dark", "mwb-theme-light", "mwb-theme-system"
    };
    GtkStyleContext *ctx;
    gint i;

    if (widget == NULL)
        return;

    ctx = gtk_widget_get_style_context(widget);
    for (i = 0; i < MWB_THEME_COUNT; i++)
        gtk_style_context_remove_class(ctx, classes[i]);
    gtk_style_context_add_class(ctx, classes[mwb->theme]);

    if (mwb->override_theme)
        gtk_style_context_add_class(ctx, "mwb-override");
    else
        gtk_style_context_remove_class(ctx, "mwb-override");
}

void
mwb_apply_theme(MorphosWorkbenchPlugin *mwb)
{
    gint i;

    if (mwb->plugin) {
        mwb_theme_widget(mwb, GTK_WIDGET(mwb->plugin));
        if (mwb->clear_bar_bg)
            gtk_style_context_add_class(gtk_widget_get_style_context(GTK_WIDGET(mwb->plugin)), "mwb-clear-bg");
        else
            gtk_style_context_remove_class(gtk_widget_get_style_context(GTK_WIDGET(mwb->plugin)), "mwb-clear-bg");
    }

    mwb_theme_widget(mwb, mwb->bar);
    if (mwb->bar) {
        if (mwb->clear_bar_bg)
            gtk_style_context_add_class(gtk_widget_get_style_context(mwb->bar), "mwb-clear-bg");
        else
            gtk_style_context_remove_class(gtk_widget_get_style_context(mwb->bar), "mwb-clear-bg");
    }
    for (i = 0; i < MWB_MENU_COUNT; i++)
        mwb_theme_widget(mwb, mwb->menus[i]);
    mwb_theme_widget(mwb, mwb->calendar_popup);
    mwb_theme_widget(mwb, mwb->volume_popup);
    mwb_theme_widget(mwb, mwb->batt_popup);
    mwb_theme_widget(mwb, mwb->wifi_popup);
    mwb_theme_widget(mwb, mwb->notify_popup);

    mwb_apply_menu_opacity(mwb);

    /* keep the custom-drawn gauges in sync with the theme/style */
    if (mwb->mem_gauge) {
        mwb_gauge_set_theme(mwb->mem_gauge, mwb->theme);
        mwb_gauge_set_style(mwb->mem_gauge, mwb->gauge_style);
    }
    if (mwb->disk_gauge) {
        mwb_gauge_set_theme(mwb->disk_gauge, mwb->theme);
        mwb_gauge_set_style(mwb->disk_gauge, mwb->gauge_style);
    }
    if (mwb->cpu_gauges[0]) {
        mwb_gauge_set_theme(mwb->cpu_gauges[0], mwb->theme);
        mwb_gauge_set_style(mwb->cpu_gauges[0], mwb->gauge_style);
    }
    if (mwb->batt_icon) {
        gtk_widget_queue_draw(mwb->batt_icon);
    }
}

const gchar *
mwb_logo_icon_name(MorphosWorkbenchLogo variant)
{
    switch (variant) {
    case MWB_LOGO_FLAT:
        return "ambient-logo-flat";
    case MWB_LOGO_MONO:
        return "ambient-logo-mono";
    case MWB_LOGO_CLASSIC:
    default:
        return MWB_ICON_NAME;
    }
}

void
mwb_apply_logo(MorphosWorkbenchPlugin *mwb)
{
    if (!mwb->logo_button)
        return;
    GtkWidget *child = gtk_bin_get_child(GTK_BIN(mwb->logo_button));
    if (child && GTK_IS_IMAGE(child)) {
        gtk_image_set_from_icon_name(GTK_IMAGE(child), mwb_logo_icon_name(mwb->logo_variant), GTK_ICON_SIZE_BUTTON);
        gtk_image_set_pixel_size(GTK_IMAGE(child), 24);
    }
}
