/*
 * Copyright (C) 2026 XFCE4 MorphOS Workbench Plugin Team
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include "morphos-workbench.h"

/* ------------------------------------------------------------------ *
 *  CSS - three Ambient themes (Classic / Dark / Light)
 *  ------------------------------------------------------------------ */

static const gchar *MWB_CSS =
  /* ---- structural base (theme independent) ---- */
  ".mwb-bar {"
  "  padding: 0;"
  "}"
  ".mwb-button {"
  "  background: transparent;"
  "  border: none;"
  "  border-radius: 0;"
  "  padding: 0 9px;"
  "  font-weight: 600;"
  "}"
  ".mwb-button:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-button:active, .mwb-button.open {"
  "  color: #ffffff;"
  "}"
  ".mwb-logo {"
  "  padding: 0 7px 0 6px;"
  "}"
  ".mwb-clocks {"
  "  background: transparent;"
  "  padding: 0 7px;"
  "  font-size: 12px;"
  "  font-weight: 600;"
  "}"
  ".mwb-separator {"
  "  min-width: 1px;"
  "  margin: 4px 3px;"
  "}"
  ".mwb-screenbar-divider {"
  "  min-width: 1px;"
  "  margin: 5px 3px;"
  "}"
  ".mwb-popup {"
  "  background-color: #18263a;"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  box-shadow: 0 8px 22px alpha(#000000, 0.60);"
  "}"
  ".mwb-popup label, .mwb-popup calendar {"
  "  color: #dbe6f2;"
  "}"
  /* ---- base menu (same chromatic look as the workbench bar) ---- */
  ".mwb-menu {"
  "  background-color: rgba(28, 42, 64, 0.98);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  border-radius: 4px;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.55);"
  "  padding: 2px 0;"
  "}"
  ".mwb-menu > menuitem {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#6ba3d9, 0.8) 0%, alpha(#3a72ad, 0.8) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.10);"
  "  min-height: 1px;"
  "  margin: 2px 0;"
  "}"
  ".mwb-settings-section {"
  "  font-weight: 700;"
  "  padding: 4px 6px;"
  "  border-top: 1px solid alpha(#ffffff, 0.28);"
  "  border-bottom: 1px solid alpha(#000000, 0.35);"
  "}"
  ".mwb-gaugebox {"
  "  background: transparent;"
  "  padding: 2px 3px;"
  "  border: 1px solid alpha(#000000, 0.55);"
  "  border-radius: 6px;"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.35);"
  "}"
  ".mwb-vgauge {"
  "  min-width: 76px;"
  "  min-height: 14px;"
  "  background: transparent;"
  "}"
  ".mwb-vgauge-label {"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  padding: 0 1px;"
  "}"
  ".mwb-gauge-value {"
  "  min-width: 34px;"
  "  font-family: monospace;"
  "  font-size: 11px;"
  "  font-weight: 700;"
  "  padding: 0 2px;"
  "}"
  ".mwb-lamp {"
  "  min-width: 8px;"
  "  min-height: 8px;"
  "  border-radius: 50%;"
  "  margin: 0 1px;"
  "}"
  ".mwb-screenbar-item {"
  "  background: transparent;"
  "  font-size: 10px;"
  "  font-weight: 600;"
  "}"
  ".mwb-volbutton {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  padding: 0 5px;"
  "  min-height: 24px;"
  "}"
  ".mwb-volbutton:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-clockbtn {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 4px;"
  "  padding: 0 4px;"
  "}"
  ".mwb-clockbtn:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic .mwb-volbutton, .mwb-theme-classic .mwb-clockbtn,"
  ".mwb-theme-dark .mwb-volbutton, .mwb-theme-dark .mwb-clockbtn {"
  "  border-top-color: alpha(#ffffff, 0.12);"
  "  border-left-color: alpha(#ffffff, 0.08);"
  "  border-right-color: alpha(#000000, 0.45);"
  "  border-bottom-color: alpha(#000000, 0.45);"
  "}"
  ".mwb-theme-light .mwb-volbutton, .mwb-theme-light .mwb-clockbtn {"
  "  border-top-color: alpha(#ffffff, 0.72);"
  "  border-left-color: alpha(#ffffff, 0.60);"
  "  border-right-color: alpha(#5b6672, 0.42);"
  "  border-bottom-color: alpha(#5b6672, 0.42);"
  "}"
  ".mwb-clockbtn .mwb-clocks {"
  "  color: inherit;"
  "}"
  ".mwb-hbox {"
  "  background: transparent;"
  "}"
  ".mwb-status-group {"
  "  padding: 0 3px;"
  "  border: 1px solid alpha(#000000, 0.45);"
  "  border-radius: 6px;"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.35);"
  "}"
  ".mwb-island {"
  "  margin: 4px 2px;"
  "  padding: 0 4px;"
  "  min-height: 18px;"
  "  border: 1px solid alpha(#000000, 0.55);"
  "  border-radius: 9px;"
  "  box-shadow: inset 0 2px 3px alpha(#000000, 0.55), inset 0 -1px 0 alpha(#ffffff, 0.16);"
  "}"
  ".mwb-title {"
  "  font-weight: 700;"
  "  padding: 0 6px;"
  "}"
  ".mwb-title.mwb-title-active {"
  "  text-shadow: 0 0 6px alpha(#6ba3d9, 0.8);"
  "}"
  ".mwb-appmenu-item {"
  "  padding: 6px 22px 6px 12px;"
  "}"
  ".mwb-appmenu-item:hover {"
  "  color: #ffffff;"
  "}"
  ".mwb-menu-workbench { min-width: 220px; }"
  ".mwb-menu-ambient { min-width: 250px; }"
  ".mwb-menu-icons { min-width: 210px; }"
  ".mwb-menu-disk { min-width: 230px; }"
  ".mwb-menu-applications { min-width: 280px; }"
  /* ---- CLASSIC theme (original Ambient dark-blue) ---- */
  ".mwb-theme-classic .mwb-bar {"
  "  background-image: linear-gradient(to bottom,"
  "    #2c3f5c 0%, #253650 35%, #1c2a40 100%);"
  "  background-color: #1c2a40;"
  "  border-top: 1px solid alpha(#ffffff, 0.18);"
  "  border-bottom: 1px solid alpha(#000000, 0.45);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.10), inset 0 -1px 0 alpha(#000000, 0.35);"
  "}"
  ".mwb-theme-classic .mwb-button,"
  ".mwb-theme-classic .mwb-volbutton,"
  ".mwb-theme-classic .mwb-clockbtn {"
  "  color: #e6edf5;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-button:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#7fb2e6, 0.55) 0%, alpha(#4a7fb8, 0.45) 100%);"
  "}"
  ".mwb-theme-classic .mwb-volbutton:hover,"
  ".mwb-theme-classic .mwb-clockbtn:hover {"
  "  background-color: alpha(#4a7fb8, 0.5);"
  "}"
  ".mwb-theme-classic .mwb-button:active, .mwb-theme-classic .mwb-button.open {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#17325a, 0.9) 0%, alpha(#2b5588, 0.7) 100%);"
  "}"
  ".mwb-theme-classic .mwb-clocks {"
  "  color: #dbe6f2;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-screenbar-item,"
  ".mwb-theme-classic .mwb-title {"
  "  color: #aebfd4;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic .mwb-title-active {"
  "  color: #eaf3ff;"
  "}"
  ".mwb-theme-classic .mwb-vgauge-label {"
  "  color: #7e8fa6;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-classic .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #0a1526 0%, #13203a 100%);"
  "  border: 1px solid alpha(#000000, 0.8);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7), 0 0 0 1px alpha(#ffffff, 0.05);"
  "}"
  ".mwb-theme-classic .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#ffffff, 0.0) 0%, alpha(#ffffff, 0.35) 50%, alpha(#ffffff, 0.0) 100%);"
  "}"
  ".mwb-theme-classic .mwb-screenbar-divider,"
  ".mwb-theme-dark .mwb-screenbar-divider {"
  "  background: alpha(#ffffff, 0.20);"
  "}"
  ".mwb-theme-classic.mwb-menu {"
  "  background-color: rgba(28, 42, 64, 0.97);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.55);"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem {"
  "  color: #dbe6f2;"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#6ba3d9, 0.75) 0%, alpha(#3a72ad, 0.75) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-classic.mwb-menu > menuitem:disabled {"
  "  color: alpha(#dbe6f2, 0.4);"
  "}"
  ".mwb-theme-classic.mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.10);"
  "}"
  ".mwb-theme-classic.mwb-popup {"
  "  background-color: rgba(24, 38, 58, 0.98);"
  "  color: #dbe6f2;"
  "  border: 1px solid #0a1526;"
  "  box-shadow: 0 8px 22px alpha(#000000, 0.6);"
  "}"
  ".mwb-theme-classic.mwb-popup label,"
  ".mwb-theme-classic.mwb-popup calendar {"
  "  color: #dbe6f2;"
  "}"
  /* ---- DARK theme (sleek near-black) ---- */
  ".mwb-theme-dark .mwb-bar {"
  "  background-image: linear-gradient(to bottom,"
  "    #1c2430 0%, #141a24 45%, #0d121a 100%);"
  "  background-color: #0d121a;"
  "  border-top: 1px solid alpha(#ffffff, 0.10);"
  "  border-bottom: 1px solid alpha(#000000, 0.6);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.06), inset 0 -1px 0 alpha(#000000, 0.5);"
  "}"
  ".mwb-theme-dark .mwb-button,"
  ".mwb-theme-dark .mwb-volbutton,"
  ".mwb-theme-dark .mwb-clockbtn {"
  "  color: #cfd8e3;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-button:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#4a8fd4, 0.5) 0%, alpha(#2c5f96, 0.4) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-volbutton:hover,"
  ".mwb-theme-dark .mwb-clockbtn:hover {"
  "  background-color: alpha(#4a8fd4, 0.45);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-button:active, .mwb-theme-dark .mwb-button.open {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#0d1f33, 0.95) 0%, alpha(#1a3a5c, 0.8) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark .mwb-clocks {"
  "  color: #c9d4e0;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-screenbar-item,"
  ".mwb-theme-dark .mwb-title {"
  "  color: #97a6b8;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-dark .mwb-title-active {"
  "  color: #e4eef8;"
  "}"
  ".mwb-theme-dark .mwb-vgauge-label {"
  "  color: #6f7e92;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.8);"
  "}"
  ".mwb-theme-dark .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #05080d 0%, #0b121c 100%);"
  "  border: 1px solid alpha(#000000, 0.9);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.8), 0 0 0 1px alpha(#ffffff, 0.04);"
  "}"
  ".mwb-theme-dark .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#ffffff, 0.0) 0%, alpha(#ffffff, 0.22) 50%, alpha(#ffffff, 0.0) 100%);"
  "}"
  ".mwb-theme-dark.mwb-menu {"
  "  background-color: rgba(12, 17, 25, 0.98);"
  "  color: #c9d4e0;"
  "  border: 1px solid #000000;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-dark.mwb-menu > menuitem {"
  "  color: #c9d4e0;"
  "}"
  ".mwb-theme-dark.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#4a8fd4, 0.8) 0%, alpha(#2c5f96, 0.8) 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-dark.mwb-menu > separator {"
  "  background: alpha(#ffffff, 0.08);"
  "}"
  ".mwb-theme-dark.mwb-popup {"
  "  background-color: rgba(10, 15, 22, 0.99);"
  "  color: #c9d4e0;"
  "  border: 1px solid #000000;"
  "  box-shadow: 0 8px 22px alpha(#000000, 0.7);"
  "}"
  ".mwb-theme-dark.mwb-popup label,"
  ".mwb-theme-dark.mwb-popup calendar {"
  "  color: #c9d4e0;"
  "}"
  /* ---- LIGHT theme (silver / classic Workbench metal) ---- */
  ".mwb-theme-light .mwb-bar {"
  "  background-image: linear-gradient(to bottom,"
  "    #f2f4f7 0%, #d9dee5 45%, #b8c0ca 100%);"
  "  background-color: #cdd4dc;"
  "  border-top: 1px solid alpha(#ffffff, 0.85);"
  "  border-bottom: 1px solid alpha(#6a7280, 0.7);"
  "  box-shadow: inset 0 1px 0 alpha(#ffffff, 0.9), inset 0 -1px 0 alpha(#87909b, 0.5);"
  "}"
  ".mwb-theme-light .mwb-button,"
  ".mwb-theme-light .mwb-volbutton,"
  ".mwb-theme-light .mwb-clockbtn {"
  "  color: #2b3440;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.6);"
  "}"
  ".mwb-theme-light .mwb-button:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#ffffff, 0.75) 0%, alpha(#b9c4d0, 0.65) 100%);"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-volbutton:hover,"
  ".mwb-theme-light .mwb-clockbtn:hover {"
  "  background-color: alpha(#b9c4d0, 0.65);"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-button:active, .mwb-theme-light .mwb-button.open {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#a9b6c4, 0.9) 0%, alpha(#c9d3dd, 0.8) 100%);"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-clocks {"
  "  color: #2b3440;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.6);"
  "}"
  ".mwb-theme-light .mwb-screenbar-item,"
  ".mwb-theme-light .mwb-title {"
  "  color: #5b6672;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.6);"
  "}"
  ".mwb-theme-light .mwb-title-active {"
  "  color: #101722;"
  "}"
  ".mwb-theme-light .mwb-vgauge-label {"
  "  color: #6a7480;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.5);"
  "}"
  ".mwb-theme-light .mwb-lamp {"
  "  background-image: linear-gradient(to bottom, #9aa4b0 0%, #c3ccd5 100%);"
  "  border: 1px solid alpha(#5b6672, 0.7);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.8), 0 0 0 1px alpha(#6a7480, 0.3);"
  "}"
  ".mwb-theme-light .mwb-separator {"
  "  background-image: linear-gradient(to bottom,"
  "    alpha(#000000, 0.0) 0%, alpha(#5b6672, 0.45) 50%, alpha(#000000, 0.0) 100%);"
  "}"
  ".mwb-theme-light .mwb-screenbar-divider {"
  "  background: alpha(#5b6672, 0.38);"
  "}"
  ".mwb-theme-classic .mwb-island, .mwb-theme-dark .mwb-island {"
  "  background: alpha(#07111e, 0.42);"
  "  border-top-color: alpha(#ffffff, 0.18);"
  "  border-left-color: alpha(#ffffff, 0.10);"
  "  border-right-color: alpha(#000000, 0.65);"
  "  border-bottom-color: alpha(#000000, 0.65);"
  "}"
  ".mwb-theme-light .mwb-island {"
  "  background: alpha(#f7f9fb, 0.42);"
  "  border-top-color: alpha(#ffffff, 0.85);"
  "  border-left-color: alpha(#ffffff, 0.65);"
  "  border-right-color: alpha(#5b6672, 0.45);"
  "  border-bottom-color: alpha(#5b6672, 0.45);"
  "}"
  ".mwb-theme-light.mwb-menu {"
  "  background-color: rgba(240, 243, 247, 0.99);"
  "  color: #2b3440;"
  "  border: 1px solid #87909b;"
  "  box-shadow: 0 6px 18px alpha(#000000, 0.25);"
  "}"
  ".mwb-theme-light.mwb-menu > menuitem {"
  "  color: #2b3440;"
  "}"
  ".mwb-theme-light.mwb-menu > menuitem:hover {"
  "  background-image: linear-gradient(to bottom,"
  "    #5a87c4 0%, #3f6da8 100%);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-light.mwb-menu > separator {"
  "  background: alpha(#2b3440, 0.12);"
  "}"
  ".mwb-theme-light.mwb-popup {"
  "  background-color: rgba(240, 243, 247, 0.99);"
  "  color: #2b3440;"
  "  border: 1px solid #87909b;"
  "  box-shadow: 0 8px 22px alpha(#000000, 0.3);"
  "}"
  ".mwb-theme-light.mwb-popup label,"
  ".mwb-theme-light.mwb-popup calendar {"
  "  color: #2b3440;"
  "}"
  /* lamp colors (shared traffic-light diodes) */
  ".mwb-lamp.net {"
  "  background-image: linear-gradient(to bottom, #b23a3a 0%, #6b1b1b 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7), 0 0 3px alpha(#b23a3a, 0.5);"
  "}"
  ".mwb-lamp.disk {"
  "  background-image: linear-gradient(to bottom, #7a5a20 0%, #3a2c0d 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#000000, 0.7);"
  "}"
  ".mwb-lamp.active-net,"
  ".mwb-lamp.active-disk {"
  "  background-image: linear-gradient(to bottom,"
  "    #fff3a0 0%, #f0a32d 60%, #b87215 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.5),"
  "    0 0 6px alpha(#f0a32d, 0.9), 0 0 12px alpha(#f0a32d, 0.4);"
  "}"
  ".mwb-lamp.active-net-high {"
  "  background-image: linear-gradient(to bottom,"
  "    #9fe3ff 0%, #37b0f0 60%, #1570b8 100%);"
  "  box-shadow: inset 0 1px 1px alpha(#ffffff, 0.5),"
  "    0 0 6px alpha(#37b0f0, 0.9), 0 0 12px alpha(#37b0f0, 0.4);"
  "}"
  ".mwb-popup scale trough {"
  "  background-image: linear-gradient(to bottom,"
  "    #0f1c30 0%, #16253d 100%);"
  "  border: 1px solid alpha(#0a1526, 0.9);"
  "  border-radius: 4px;"
  "  min-height: 8px;"
  "}"
  ".mwb-popup scale highlight {"
  "  background-image: linear-gradient(to bottom,"
  "    #8fd0ff 0%, #3f8fe0 60%, #2b6cb0 100%);"
  "  border: none;"
  "  border-radius: 4px;"
  "}"
  ".mwb-popup scale slider {"
  "  background-image: linear-gradient(to bottom,"
  "    #eaf4ff 0%, #b8d4f0 100%);"
  "  border: 1px solid #0a1526;"
  "  border-radius: 8px;"
  "  min-width: 14px;"
  "  min-height: 14px;"
  "}"
  ".mwb-theme-light.mwb-popup scale trough {"
  "  background-image: linear-gradient(to bottom, #d9dee5 0%, #b8c0ca 100%);"
  "  border-color: alpha(#6a7280, 0.7);"
  "}"
  ".mwb-theme-light.mwb-popup scale highlight {"
  "  background-image: linear-gradient(to bottom, #8fc0ff 0%, #4a87d4 100%);"
  "}"
  ".mwb-theme-light.mwb-popup scale slider {"
  "  background-image: linear-gradient(to bottom, #ffffff 0%, #cdd4dc 100%);"
  "  border-color: #6a7280;"
  "}"
  /* ---- stronger selected / focused states ---- */
  ".mwb-button:focus, .mwb-volbutton:focus, .mwb-clockbtn:focus,"
  ".mwb-button:active, .mwb-volbutton:active, .mwb-clockbtn:active {"
  "  outline: 1px solid alpha(#6ba3d9, 0.75);"
  "  outline-offset: -1px;"
  "}"
  ".mwb-menu > menuitem:hover,"
  ".mwb-menu > menuitem:selected {"
  "  box-shadow: inset 2px 0 0 alpha(#6ba3d9, 0.9);"
  "}"
  /* ---- Embedded xfce4-networkmanager button — match the screenbar ---- */
  ".nm-panel-button {"
  "  background: transparent;"
  "  border: 1px solid transparent;"
  "  border-radius: 5px;"
  "  padding: 0 5px;"
  "  min-height: 24px;"
  "}"
  ".mwb-theme-classic .nm-panel-button,"
  ".mwb-theme-dark .nm-panel-button {"
  "  color: #e6edf5;"
  "  text-shadow: 0 1px 1px alpha(#000000, 0.6);"
  "  border-top-color: alpha(#ffffff, 0.12);"
  "  border-left-color: alpha(#ffffff, 0.08);"
  "  border-right-color: alpha(#000000, 0.45);"
  "  border-bottom-color: alpha(#000000, 0.45);"
  "}"
  ".mwb-theme-light .nm-panel-button {"
  "  color: #2b3440;"
  "  text-shadow: 0 1px 0 alpha(#ffffff, 0.6);"
  "  border-top-color: alpha(#ffffff, 0.72);"
  "  border-left-color: alpha(#ffffff, 0.60);"
  "  border-right-color: alpha(#5b6672, 0.42);"
  "  border-bottom-color: alpha(#5b6672, 0.42);"
  "}"
  ".mwb-theme-classic .nm-panel-button:hover,"
  ".mwb-theme-classic .nm-panel-button.open,"
  ".mwb-theme-dark .nm-panel-button:hover,"
  ".mwb-theme-dark .nm-panel-button.open {"
  "  background-color: alpha(#4a7fb8, 0.5);"
  "  color: #ffffff;"
  "}"
  ".mwb-theme-light .nm-panel-button:hover,"
  ".mwb-theme-light .nm-panel-button.open {"
  "  background-color: alpha(#b9c4d0, 0.65);"
  "  color: #101722;"
  "}"
  /* ---- Workbench override: pin down every widget so the desktop theme
   *      cannot leak through. Applied to the bar, menus and popups when
   *      "Override GTK theme" is enabled. ---- */
  ".mwb-override.mwb-menu > menuitem {"
  "  min-height: 24px;"
  "  padding: 2px 8px;"
  "}"
  ".mwb-override .mwb-menu > separator {"
  "  min-height: 1px;"
  "}"
  ".mwb-override.mwb-popup calendar {"
  "  background: transparent;"
  "}"
  ".mwb-override .mwb-popup scale trough {"
  "  border-radius: 9999px;"
  "}"
  ".mwb-override .mwb-gaugebox {"
  "  border-radius: 8px;"
  "}"
  ".mwb-override .mwb-volbutton,"
  ".mwb-override .mwb-clockbtn {"
  "  border-radius: 5px;"
  "}"
  ".mwb-override .mwb-button:hover,"
  ".mwb-override .mwb-volbutton:hover,"
  ".mwb-override .mwb-clockbtn:hover {"
  "  box-shadow: inset 0 0 0 1px alpha(#6ba3d9, 0.45);"
  "}"
  "";

void
mwb_init_css(void)
{
    static gboolean loaded = FALSE;
    if (loaded)
        return;
    loaded = TRUE;

    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_data(provider, MWB_CSS, -1, NULL);
    gtk_style_context_add_provider_for_screen(gdk_screen_get_default(),
                                              GTK_STYLE_PROVIDER(provider),
                                              GTK_STYLE_PROVIDER_PRIORITY_USER);
    g_object_unref(provider);
}

void
mwb_theme_widget(MorphosWorkbenchPlugin *mwb, GtkWidget *widget)
{
    static const gchar *classes[MWB_THEME_COUNT] = {
        "mwb-theme-classic", "mwb-theme-dark", "mwb-theme-light"
    };
    GtkStyleContext *ctx;
    gint i;

    if (widget == NULL)
        return;

    ctx = gtk_widget_get_style_context(widget);
    for (i = 0; i < MWB_THEME_COUNT; i++)
        gtk_style_context_remove_class(ctx, classes[i]);
    gtk_style_context_add_class(ctx, classes[mwb->theme]);

    if (mwb->override_theme)
        gtk_style_context_add_class(ctx, "mwb-override");
    else
        gtk_style_context_remove_class(ctx, "mwb-override");
}

void
mwb_apply_theme(MorphosWorkbenchPlugin *mwb)
{
    gint i;

    mwb_theme_widget(mwb, mwb->bar);
    for (i = 0; i < MWB_MENU_COUNT; i++)
        mwb_theme_widget(mwb, mwb->menus[i]);
    mwb_theme_widget(mwb, mwb->calendar_popup);
    mwb_theme_widget(mwb, mwb->volume_popup);

    /* keep the custom-drawn gauges in sync with the theme/style */
    if (mwb->mem_gauge) {
        mwb_gauge_set_theme(mwb->mem_gauge, mwb->theme);
        mwb_gauge_set_style(mwb->mem_gauge, mwb->gauge_style);
    }
    if (mwb->disk_gauge) {
        mwb_gauge_set_theme(mwb->disk_gauge, mwb->theme);
        mwb_gauge_set_style(mwb->disk_gauge, mwb->gauge_style);
    }
    if (mwb->cpu_gauges[0]) {
        mwb_gauge_set_theme(mwb->cpu_gauges[0], mwb->theme);
        mwb_gauge_set_style(mwb->cpu_gauges[0], mwb->gauge_style);
    }
}

const gchar *
mwb_logo_icon_name(MorphosWorkbenchLogo variant)
{
    switch (variant) {
    case MWB_LOGO_FLAT:
        return "ambient-logo-flat";
    case MWB_LOGO_MONO:
        return "ambient-logo-mono";
    case MWB_LOGO_CLASSIC:
    default:
        return MWB_ICON_NAME;
    }
}

void
mwb_apply_logo(MorphosWorkbenchPlugin *mwb)
{
    if (!mwb->logo_button)
        return;
    GtkWidget *child = gtk_bin_get_child(GTK_BIN(mwb->logo_button));
    if (child && GTK_IS_IMAGE(child))
        gtk_image_set_from_icon_name(GTK_IMAGE(child), mwb_logo_icon_name(mwb->logo_variant), GTK_ICON_SIZE_BUTTON);
}
